#
# ssh-keygen -t rsa -P ''
# ssh root@{10.10.107.151 10.10.107.152}
---
- hosts: all
  tasks:
    - name: Push rsa public key to all machines
      authorized_key: user={{ ansible_ssh_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
