#!/bin/bash
docker run \
  --restart=on-failure:5 \
  --env-file=/etc/etcd.env \
  --net=host \
  -v /etc/ssl/certs:/etc/ssl/certs:ro \
  -v {{ etcd_cert_dir }}:{{ etcd_cert_dir }}:ro \
  -v {{ etcd_data_dir }}:/var/lib/etcd:rw \
  {% if etcd_memory_limit is defined %}
  --memory={{ etcd_memory_limit|regex_replace('Mi', 'M') }} \
  {% endif %}
  {% if etcd_cpu_limit is defined %}
  --cpu-shares={{ etcd_cpu_limit|regex_replace('m', '') }} \
  {% endif %}
  --name={{ etcd_member_name | default("etcd") }} \
  registry.cn-hangzhou.aliyuncs.com/google-containers/etcd-amd64:3.0.17 \
    /usr/local/bin/etcd \
  "$@"
