---
- name: restart etcd
  command: /bin/true
  notify:
    - etcd | reload systemd
    - reload etcd
    - wait for etcd up

- name: etcd | reload systemd
  command: systemctl daemon-reload

- name: reload etcd
  service:
    name: etcd
    state: restarted

- name: wait for etcd up
  uri:
    url: "http://127.0.0.1:2379/health"
    validate_certs: no
  register: result
  until: result.status is defined and result.status == 200
  retries: 10
  delay: 5

  